use coustmer_purchasing_behaviour;
select * from project;
#what is total revanue generated by male vs female coustmers?
SELECT 
    gender, SUM(purchase_amount) AS revanue
FROM
    project
    group by gender;
    
# which coustmers uesd a discount but still spent more than the average purchase amount
select customer_id,purchase_amount from project
where discount_applied="yes" and purchase_amount>=(select avg(purchase_amount) from project);

# which are the top 5 products with highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_product_rating from project
group by item_purchased
order by avg(review_rating) desc
limit 5;

# compare the average Purchase amonut between standard and express shipping
select shipping_type, avg(purchase_amount) from project
where shipping_type in ("standard", "express")
group by shipping_type;

# do subsrcibe coustmers sepnd more ? compare average spend and total revane  between subscribe and non_subscribe.
select subscription_status,
count(customer_id) as total_coustmers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revanue
from project
group by subscription_status
order by total_revanue, avg_spend desc;

# which 5 products have the highest percentage with discount applied?
select item_purchased,
sum(case when discount_applied = "yes" then 1 else 0 end )/count(*) * 100 as discount_rate
from project
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 # segment coustmer into new , returing , and loyal and loyal based on their total number of previous purchase and show the count of each segment .
 # write CTE
 with customer_type as(
 select customer_id,previous_purchases,
 case
    when previous_purchases=1 then "new"
    when previous_purchases Between 2 and 10 then "returning"
    else "Loyal"
    end as customer_segment
    from project
)
select customer_segment,count(*) as "number_of_customers"
from customer_type
group by customer_segment;

# what are the top 3 most purchased products with in each category?
# write cte
with  item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) Desc) as item_rank from project 
group by category , item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
# are customers who are repeat buyers (more then 5 previous purchases ) also likely to subscribe ?
select subscription_status,
count(customer_id) as repeat_buyers
from project
where previous_purchases>5
group by subscription_status;

# what is the revenue contribution of each age group ?

select age_group,
sum(purchase_amount) as total_revenue
from project
group by age_group
order by total_revenue desc;

#
